version: '3.7'
services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - ./mariadb/data:/var/lib/mysql
    env_file:
      - path: environment/mysql.env
      - path: environment/mysql-admin.env
    networks: [db]
  judge:
    build:
      context: .
      dockerfile: ./judge/Dockerfile
    restart: unless-stopped
    env_file:
      - path: environment/judge.env
      - path: environment/mysql.env
    environment:
      - BRIDGED_PORT=9999
      - BRIDGED_HOST=dmoj-bridged
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dmoj/problems/:/problems/
      - ./sandbox/:/sandbox
      - ./logs/:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [db, bridged]
networks:
  db:
  bridged:
    name: dmoj_bridged
    external: true
