version: '3.7'
services:
  db:
    container_name: judge_mysql
    image: mariadb:11.5
    restart: always
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - ./mariadb/data:/var/lib/mysql
    env_file: [environment/mysql.env, environment/mysql-admin.env]
    networks: [db]
  judge:
    build:
      context: .
      dockerfile: ./judge/Dockerfile
    restart: unless-stopped
    ports:
      - 9998:9998
    env_file:
      - path: ./environment/judge.env
        required: true
    environment:
      - BRIDGED_PORT=9999
      - BRIDGED_HOST=dmoj-bridged
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dmoj/problems:/problems 
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [db, bridged]
networks:
  db:
  bridged:
    name: dmoj_bridged
    external: true
